# This file was generated by GoReleaser. DO NOT EDIT.
cask "hydra" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "becd9f63928a213c74897d2283259725243349e4db403b0fbedf9a0b7ef6a6cf"
      url "https://github.com/hydra-gitops/hydra/releases/download/v#{version}/hydra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b675c7a7b4d74fd315ef137adb23bad3c199a2bc6aa5c1facc4c3dbf38bf05a"
      url "https://github.com/hydra-gitops/hydra/releases/download/v#{version}/hydra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b600517b9c57000056c7890e109db2b8027a20aa65207ab5ade24a66b30bc713"
      url "https://github.com/hydra-gitops/hydra/releases/download/v#{version}/hydra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6eea9a51830b098fbbf6fe44665d500a44bc96fa4173a7ddfa3c0cd3868b5bf"
      url "https://github.com/hydra-gitops/hydra/releases/download/v#{version}/hydra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hydra"
  desc "Hydra GitOps CLI for Kubernetes cluster management"
  homepage "https://hydra-gitops.org/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hydra"

  # No zap stanza required

end
