# typed: false
# frozen_string_literal: true

# This file is generated by the Hydra publish workflow. DO NOT EDIT.
cask "hydra-bin" do
  version "1.2.4"
  name "Hydra"
  desc "Hydra GitOps CLI binary for Kubernetes cluster management"
  homepage "https://hydra-gitops.org/"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hydra-gitops/hydra/releases/download/v1.2.4/hydra_#{version}_darwin_arm64.tar.gz"
      sha256 "c1862216a2170440a12940de03eb0205a2e3574f36c0e8040bd8c3c5e8c467b5"
    else
      url "https://github.com/hydra-gitops/hydra/releases/download/v1.2.4/hydra_#{version}_darwin_amd64.tar.gz"
      sha256 "475fc7bb3ac30e105be8150f3cf8900853ee41e7daad95b88e9d72f2a7a83d18"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hydra-gitops/hydra/releases/download/v1.2.4/hydra_#{version}_linux_arm64.tar.gz"
      sha256 "0626641430d8cf0485114a14126b95ecef9b3c5edc40cd89a3ebad3b4296f336"
    else
      url "https://github.com/hydra-gitops/hydra/releases/download/v1.2.4/hydra_#{version}_linux_amd64.tar.gz"
      sha256 "4f5448c570119b565067401b037b350ad8fa47aef96802f09579ac2058b55345"
    end
  end

  binary "hydra"
end
