# typed: false
# frozen_string_literal: true

# This file is generated by the Hydra publish workflow. DO NOT EDIT.
cask "hydra-bin" do
  version "1.2.8"
  name "Hydra"
  desc "Hydra GitOps CLI binary for Kubernetes cluster management"
  homepage "https://hydra-gitops.org/"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hydra-gitops/hydra/releases/download/v1.2.8/hydra_#{version}_darwin_arm64.tar.gz"
      sha256 "2afd25db85d4f5ef952546f54e814746c7167b9af6d61d47ec9eaeaad9ed6650"
    else
      url "https://github.com/hydra-gitops/hydra/releases/download/v1.2.8/hydra_#{version}_darwin_amd64.tar.gz"
      sha256 "2e99eff2df7be0029d14a36dbf6bfc54976b12ccfc62886bd2478bc24395bbd1"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hydra-gitops/hydra/releases/download/v1.2.8/hydra_#{version}_linux_arm64.tar.gz"
      sha256 "76aa61236366ea140dd17628f985002b21142a61e5c1af5d4fdc16bdf0fda5f9"
    else
      url "https://github.com/hydra-gitops/hydra/releases/download/v1.2.8/hydra_#{version}_linux_amd64.tar.gz"
      sha256 "2952e8fa8446812f9f4b06d6415304d3abadbb3239306c0ac595b12a41a21557"
    end
  end

  binary "hydra"
end
