# This file was generated by GoReleaser. DO NOT EDIT.
cask "hydra-bin" do
  version "1.2.3"

  on_macos do
    on_intel do
      sha256 "631fa9006d0385e307caa7111e6d1ae5f9ff4ab08ed0ad0c50262ba3b7ba363d"
      url "https://github.com/hydra-gitops/hydra/releases/download/v#{version}/hydra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb380cb68ea63546607b1ec9873800cc54d246f9f32a9140643a0cd9902f53f7"
      url "https://github.com/hydra-gitops/hydra/releases/download/v#{version}/hydra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b27ed8394bf126491cacadbe7ef5e5727b1265acf94736f5c9b54950640adbff"
      url "https://github.com/hydra-gitops/hydra/releases/download/v#{version}/hydra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a864d58935e35b6569f12da25514f7bc7371deae6ba7ad5a453e56252a2620f"
      url "https://github.com/hydra-gitops/hydra/releases/download/v#{version}/hydra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hydra-bin"
  desc "Hydra GitOps CLI binary for Kubernetes cluster management"
  homepage "https://hydra-gitops.org/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hydra"

  # No zap stanza required

end
