# typed: false
# frozen_string_literal: true

# This file is generated by the Hydra publish workflow. DO NOT EDIT.
class Hydra < Formula
  desc "Hydra GitOps CLI for Kubernetes cluster management"
  homepage "https://hydra-gitops.org/"
  version "1.2.9"
  license "Apache-2.0"

  depends_on "go" => :build

  url "https://github.com/hydra-gitops/hydra/archive/refs/tags/v1.2.9.tar.gz"
  sha256 "7e85610495f383fe9bd6319781866a902943ddf70ce9c0d9abddc8652026b144"

  def install
    cd "hydra-go" do
      system "go", "build", *std_go_args(ldflags: "-s -w -X hydra-gitops.org/hydra/hydra-go/base/buildinfo.Version=#{version} -X hydra-gitops.org/hydra/hydra-go/base/buildinfo.TagSHA=236622a6a093e40a803999edcd6c145b7256bbce"), "./cli"
    end
  end

  test do
    assert_match "Hydra", shell_output("#{bin}/hydra --help")
  end
end
